"""created Indexes for Invoices table for user_id and created_at

Revision ID: 39e840a9d727
Revises: 871c0fffb703
Create Date: 2025-09-29 14:37:16.202563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e840a9d727'
down_revision: Union[str, Sequence[str], None] = '871c0fffb703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_category_created_at', 'invoices', ['category_id', 'created_at'], unique=False)
    op.create_index('idx_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('idx_user_created_at', 'invoices', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_id', 'invoices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='invoices')
    op.drop_index('idx_user_created_at', table_name='invoices')
    op.drop_index('idx_created_at', table_name='invoices')
    op.drop_index('idx_category_created_at', table_name='invoices')
    # ### end Alembic commands ###
