"""adding new column named last_run_date in Income table and its index with next_due_date and is_recurring

Revision ID: 9cf3aaf46538
Revises: c31a7e422b50
Create Date: 2025-10-15 17:42:10.016141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf3aaf46538'
down_revision: Union[str, Sequence[str], None] = 'c31a7e422b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('last_run_date', sa.Date(), nullable=True))
    op.create_index('indx_recurring_incomes', 'incomes', ['next_due_date', 'last_run_date'], unique=False, postgresql_where=sa.text('is_recurring = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('indx_recurring_incomes', table_name='incomes', postgresql_where=sa.text('is_recurring = TRUE'))
    op.drop_column('incomes', 'last_run_date')
    # ### end Alembic commands ###
