"""Add Income and IncomeCategory tables and their relationships with each other and with the other tables

Revision ID: a37a8240a330
Revises: b7f83f7b64ee
Create Date: 2025-10-04 14:13:11.311966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37a8240a330'
down_revision: Union[str, Sequence[str], None] = 'b7f83f7b64ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
