"""Add invoice_name Column_and create the table again

Revision ID: b7f83f7b64ee
Revises: 
Create Date: 2025-09-30 22:06:12.754555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f83f7b64ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('invoice_name', sa.String(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_created_at', 'invoices', ['category_id', 'created_at'], unique=False)
    op.create_index('idx_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('idx_invoice_name', 'invoices', ['invoice_name'], unique=False)
    op.create_index('idx_user_created_at', 'invoices', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_id', 'invoices', ['user_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index('idx_user_id', table_name='invoices')
    op.drop_index('idx_user_created_at', table_name='invoices')
    op.drop_index('idx_invoice_name', table_name='invoices')
    op.drop_index('idx_created_at', table_name='invoices')
    op.drop_index('idx_category_created_at', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
