"""Add user_balance table

Revision ID: c31a7e422b50
Revises: d6f97eb8c647
Create Date: 2025-10-13 14:19:44.000429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31a7e422b50'
down_revision: Union[str, Sequence[str], None] = 'd6f97eb8c647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_balance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_balance')
    # ### end Alembic commands ###
