"""create some indexes

Revision ID: d6f97eb8c647
Revises: 3e1c918b1c95
Create Date: 2025-10-10 14:54:40.366723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f97eb8c647'
down_revision: Union[str, Sequence[str], None] = '3e1c918b1c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_incmoes_user_id_category_id', 'incomes', ['user_id', 'category_id'], unique=False)
    op.create_index('idx_incomes_created_at', 'incomes', ['created_at'], unique=False)
    op.create_index('idx_incomes_is_recurring', 'incomes', ['is_recurring'], unique=False)
    op.create_index('idx_incomes_user_id', 'incomes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_incomes_user_id', table_name='incomes')
    op.drop_index('idx_incomes_is_recurring', table_name='incomes')
    op.drop_index('idx_incomes_created_at', table_name='incomes')
    op.drop_index('idx_incmoes_user_id_category_id', table_name='incomes')
    # ### end Alembic commands ###
