"""initial

Revision ID: f66b99b5f258
Revises: 
Create Date: 2025-11-26 09:48:41.188212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66b99b5f258'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('income_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_income_categories_id'), 'income_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_interval', sa.String(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['income_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incmoes_user_id_category_id', 'incomes', ['user_id', 'category_id'], unique=False)
    op.create_index('idx_incomes_created_at', 'incomes', ['created_at'], unique=False)
    op.create_index('idx_incomes_is_recurring', 'incomes', ['is_recurring'], unique=False)
    op.create_index('idx_incomes_user_id', 'incomes', ['user_id'], unique=False)
    op.create_index('indx_recurring_incomes', 'incomes', ['next_due_date', 'last_run_date'], unique=False, postgresql_where=sa.text('is_recurring = TRUE'))
    op.create_index(op.f('ix_incomes_id'), 'incomes', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('invoice_name', sa.String(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurring_interval', sa.String(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_created_at', 'invoices', ['category_id', 'created_at'], unique=False)
    op.create_index('idx_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('idx_invoice_name', 'invoices', ['invoice_name'], unique=False)
    op.create_index('idx_recurring_invoices', 'invoices', ['next_due_date', 'last_run_date'], unique=False, postgresql_where=sa.text('is_recurring = TRUE'))
    op.create_index('idx_user_created_at', 'invoices', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_id', 'invoices', ['user_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('user_balance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_balance')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index('idx_user_id', table_name='invoices')
    op.drop_index('idx_user_created_at', table_name='invoices')
    op.drop_index('idx_recurring_invoices', table_name='invoices', postgresql_where=sa.text('is_recurring = TRUE'))
    op.drop_index('idx_invoice_name', table_name='invoices')
    op.drop_index('idx_created_at', table_name='invoices')
    op.drop_index('idx_category_created_at', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_incomes_id'), table_name='incomes')
    op.drop_index('indx_recurring_incomes', table_name='incomes', postgresql_where=sa.text('is_recurring = TRUE'))
    op.drop_index('idx_incomes_user_id', table_name='incomes')
    op.drop_index('idx_incomes_is_recurring', table_name='incomes')
    op.drop_index('idx_incomes_created_at', table_name='incomes')
    op.drop_index('idx_incmoes_user_id_category_id', table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_income_categories_id'), table_name='income_categories')
    op.drop_table('income_categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
